### ISSUE TITLE
Genome Package for hg38

### ISSUE THREAD

**Issue by DarioS** [polyactis/Accurity#3]
1000 Genomes Project results have been [converted to hg38](http://www.internationalgenome.org/announcements/updated-GRCh38-liftover/). Can there be an Accurity genome package created for it and made downloadable on the website or instructions for creating the package be added to the website? Currently, there is only one package for hg19 downloadable and no instructions for creating a genome package for a user's different need.

**Comment by polyactis** [comment]
we will address this issue shortly and post the reference data online.

**Comment by polyactis** [comment]
Hi Dario,

We have provided a hs38d1 package,
https://www.yfish.org/display/PUB/Accurity#Accurity-Thereferencegenomepackage

You gotta download the latest docker image
https://cloud.docker.com/u/polyactis/repository/docker/polyactis/accurity_ubuntu
to use this package. We made a few tweaks to make it easier to switch
between different genomes.

Let us know if you have any questions
