### ISSUE TITLE
Outdated Configuration File Example

### ISSUE THREAD

**Issue by DarioS** [polyactis/Accurity#4]
The documentation's example of a configuration file is relevant to older versions of Accurity which use `freebayes` but it's not clear how to adapt it for Strelka2.

```
caller_path    /program/bin/freebayes
```

Strelka2 is a couple of Python scripts and I am not sure which one to specify and in what format. In my previous simple variant analysis, I used

```
configureStrelkaSomaticWorkflow.py --referenceFasta $GENO --normalBam $N --tumorBam $T --runDir $WORKDIR
$WORKDIR/runWorkflow.py -m local -j 32
```

There's no explanation if this line of the configuration file can be blank if the user has the VCF files created (and uses `-s 2`) or if `caller_path` is always mandatory. Regardless of processing from Step 2, some users will start at the beginning and use Strelka2 calling built into Accurity, so the example needs updating.

**Comment by polyactis** [comment]
it is the path of the folder that contains all Strelka2 code/executables,
i.e. /usr/local/strelka.

you can check it inside the docker,
https://www.yfish.org/display/PUB/Accurity#Accurity-Docker

The docker, https://hub.docker.com/r/polyactis/accurity_ubuntu/, contains
the latest developer version while https://www.yfish.org/accurity/,
https://github.com/polyactis/Accurity are old stable versions. The stable
version does not use strelka.
